apiVersion: apps/v1
kind: Deployment
metadata:
  name: srikandi-app-full
  namespace: default
spec:
  selector:
    matchLabels:
      app: srikandi-app
      type: full
  template:
    metadata:
      labels:
        app: srikandi-app
        type: full
    spec:
      containers:
      - name: srikandi-app
        image: IMAGE
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: srikandi-app
  namespace: default
spec:
  selector:
    app: srikandi-app
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: srikandi-app-destionationrule
  namespace: default
spec:
  host: srikandi-app.default.svc.cluster.local
  subsets:
  - name: full # DNS-1123 label naming conventions
    labels:
      type: full
  - name: full # DNS-1123 label naming conventions
    labels:
      type: canary

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: srikandi-app-virtualservice
  namespace: default
spec:
  hosts:
  - srikandi-app.default.svc.cluster.local
  http:
  - name: "full route"
    route:
    - destination:
        host: srikandi-app.default.svc.cluster.local
        subset: full
      weight: 100 